INSERT INTO kelas VALUES
                    ('dpib12023', 'X DPIB 1', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib22023', 'X DPIB 2', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib32023', 'X DPIB 3', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib42023', 'X DPIB 4', 'Desain Pemodelan Informasi Bangunan'),
                    ('te12023', 'X TE 1', 'Teknik Elektronika'),
                    ('te22023', 'X TE 2', 'Teknik Elektronika'),
                    ('te32023', 'X TE 3', 'Teknik Elektronika'),
                    ('tk12023', 'X TK 1', 'Teknik Ketenagalistrikan'),
                    ('tk22023', 'X TK 2', 'Teknik Ketenagalistrikan'),
                    ('tk32023', 'X TK 3', 'Teknik Ketenagalistrikan'),
                    ('tk42023', 'X TK 4', 'Teknik Ketenagalistrikan'),
                    ('tm12023', 'X TM 1', 'Teknik Mesin'),
                    ('tm22023', 'X TM 2', 'Teknik Mesin'),
                    ('tm32023', 'X TM 3', 'Teknik Mesin'),
                    ('tm42023', 'X TM 4', 'Teknik Mesin'),
                    ('to12023', 'X TO 1', 'Teknik Otomotif'),
                    ('to22023', 'X TO 2', 'Teknik Otomotif'),
                    ('to32023', 'X TO 3', 'Teknik Otomotif'),
                    ('to42023', 'X TO 4', 'Teknik Otomotif'),
                    ('tjkt12023', 'X TJKT 1', 'Teknik Jaringan Komputer dan Telekomunikasi'),
                    ('tjkt22023', 'X TJKT 2', 'Teknik Jaringan Komputer dan Telekomunikasi'),
                    ('pplg2023', 'X PPLG', 'Pengembangan Perangkat Lunak dan Gim'),
                    ('bp12023', 'X BP 1', 'Broadcasting dan Perfilman'),
                    ('bp22023', 'X BP 2', 'Broadcasting dan Perfilman'),
                    ('dpib12022', 'XI DPIB 1', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib22022', 'XI DPIB 2', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib32022', 'XI DPIB 3', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib42022', 'XI DPIB 4', 'Desain Pemodelan Informasi Bangunan'),
                    ('te12022', 'XI TE 1', 'Teknik Elektronika'),
                    ('te22022', 'XI TE 2', 'Teknik Elektronika'),
                    ('te32022', 'XI TE 3', 'Teknik Elektronika'),
                    ('tk12022', 'XI TK 1', 'Teknik Ketenagalistrikan'),
                    ('tk22022', 'XI TK 2', 'Teknik Ketenagalistrikan'),
                    ('tk32022', 'XI TK 3', 'Teknik Ketenagalistrikan'),
                    ('tk42022', 'XI TK 4', 'Teknik Ketenagalistrikan'),
                    ('tm12022', 'XI TM 1', 'Teknik Mesin'),
                    ('tm22022', 'XI TM 2', 'Teknik Mesin'),
                    ('tm32022', 'XI TM 3', 'Teknik Mesin'),
                    ('tm42022', 'XI TM 4', 'Teknik Mesin'),
                    ('to12022', 'XI TO 1', 'Teknik Otomotif'),
                    ('to22022', 'XI TO 2', 'Teknik Otomotif'),
                    ('to32022', 'XI TO 3', 'Teknik Otomotif'),
                    ('to42022', 'XI TO 4', 'Teknik Otomotif'),
                    ('tjkt12022', 'XI TJKT 1', 'Teknik Jaringan Komputer dan Telekomunikasi'),
                    ('tjkt22022', 'XI TJKT 2', 'Teknik Jaringan Komputer dan Telekomunikasi'),
                    ('pplg2022', 'XI PPLG', 'Pengembangan Perangkat Lunak dan Gim'),
                    ('bp12022', 'XI BP 1', 'Broadcasting dan Perfilman'),
                    ('bp22022', 'XI BP 2', 'Broadcasting dan Perfilman'),
                    ('dpib12021', 'XII DPIB 1', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib22021', 'XII DPIB 2', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib32021', 'XII DPIB 3', 'Desain Pemodelan Informasi Bangunan'),
                    ('dpib42021', 'XII DPIB 4', 'Desain Pemodelan Informasi Bangunan'),
                    ('te12021', 'XII TE 1', 'Teknik Elektronika'),
                    ('te22021', 'XII TE 2', 'Teknik Elektronika'),
                    ('te32021', 'XII TE 3', 'Teknik Elektronika'),
                    ('tk12021', 'XII TK 1', 'Teknik Ketenagalistrikan'),
                    ('tk22021', 'XII TK 2', 'Teknik Ketenagalistrikan'),
                    ('tk32021', 'XII TK 3', 'Teknik Ketenagalistrikan'),
                    ('tk42021', 'XII TK 4', 'Teknik Ketenagalistrikan'),
                    ('tm12021', 'XII TM 1', 'Teknik Mesin'),
                    ('tm22021', 'XII TM 2', 'Teknik Mesin'),
                    ('tm32021', 'XII TM 3', 'Teknik Mesin'),
                    ('tm42021', 'XII TM 4', 'Teknik Mesin'),
                    ('to12021', 'XII TO 1', 'Teknik Otomotif'),
                    ('to22021', 'XII TO 2', 'Teknik Otomotif'),
                    ('to32021', 'XII TO 3', 'Teknik Otomotif'),
                    ('to42021', 'XII TO 4', 'Teknik Otomotif'),
                    ('tjkt12021', 'XII TJKT 1', 'Teknik Jaringan Komputer dan Telekomunikasi'),
                    ('tjkt22021', 'XII TJKT 2', 'Teknik Jaringan Komputer dan Telekomunikasi'),
                    ('pplg2021', 'XII PPLG', 'Pengembangan Perangkat Lunak dan Gim'),
                    ('bp12021', 'XII BP 1', 'Broadcasting dan Perfilman'),
                    ('bp22021', 'XII BP 2', 'Broadcasting dan Perfilman')